// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/banners). Re-run the
// export after publishing changes there, then rebuild and redeploy.

export type Banner = { url: string; altText: string | null };

export const banners: Banner[] = [
  { url: "/assets/masterbatch-banner.webp", altText: "Iris Polymere masterbatch product range — color, white, black and filler masterbatch" }
];
