// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/certificates).

import type { LocalizedText } from "./blog";

export type CertificateData = {
  key: string;
  title: LocalizedText;
  desc: LocalizedText;
  pdfUrl: string | null;
};

export const certificates: CertificateData[] = [
  {
    key: "eco",
    title: { en: `Eco Friendly`, fr: `Éco-Responsable`, ar: `صديق للبيئة` },
    desc: { en: `Reference marker for resource-efficient and lower-impact formulation approaches.`, fr: `Repère de référence pour des approches de formulation économes en ressources et à impact réduit.`, ar: `مرجع لنُهج التركيب الموفّرة للموارد والأقل تأثيرًا بيئيًا.` },
    pdfUrl: null,
  },
  {
    key: "iso",
    title: { en: `ISO 9001`, fr: `ISO 9001`, ar: `ISO 9001` },
    desc: { en: `ISO 9001 is the international reference standard for quality management systems, covering consistent process control, documentation and continuous improvement.`, fr: `L'ISO 9001 est la norme internationale de référence pour les systèmes de management de la qualité, couvrant la maîtrise des processus, la documentation et l'amélioration continue.`, ar: `معيار ISO 9001 هو المعيار المرجعي الدولي لأنظمة إدارة الجودة، ويشمل ضبط العمليات والتوثيق والتحسين المستمر.` },
    pdfUrl: null,
  },
  {
    key: "reach",
    title: { en: `REACH`, fr: `REACH`, ar: `REACH` },
    desc: { en: `REACH is the EU regulatory framework for the Registration, Evaluation, Authorisation and Restriction of Chemicals, relevant to raw material and compound handling.`, fr: `REACH est le cadre réglementaire européen relatif à l'enregistrement, l'évaluation, l'autorisation et la restriction des substances chimiques, pertinent pour la gestion des matières premières et des compounds.`, ar: `REACH هو الإطار التنظيمي الأوروبي لتسجيل المواد الكيميائية وتقييمها وترخيصها وتقييدها، وهو ذو صلة بمناولة المواد الخام والمركّبات.` },
    pdfUrl: null,
  },
  {
    key: "rohs",
    title: { en: `RoHS`, fr: `RoHS`, ar: `RoHS` },
    desc: { en: `RoHS restricts the use of specific hazardous substances in materials, a reference point considered in relevant compound formulations.`, fr: `La directive RoHS restreint l'utilisation de certaines substances dangereuses, un point de référence pris en compte dans les formulations concernées.`, ar: `تقيّد لائحة RoHS استخدام مواد خطرة معيّنة، وهي مرجع يؤخذ بعين الاعتبار في التركيبات ذات الصلة.` },
    pdfUrl: null,
  }
];
