// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages/*). Re-run the
// export after publishing changes there, then rebuild and redeploy.

import type { LocalizedImage } from "./image-types";

export const corporateHeroImages: Record<string, LocalizedImage> = {
  "about": { en: { src: "/uploads/a5d077e4-c04c-49f2-aabf-e32c438305e4.png", width: 2400, height: 1050 }, fr: { src: "/uploads/6c7b51a0-8d59-4688-a017-4e3b65d94d28.png", width: 2400, height: 1050 }, ar: { src: "/uploads/9d24dee1-c5ce-44c5-a16f-398ece046744.png", width: 2400, height: 1050 } }
};
