// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages). Re-run the
// export after publishing changes there, then rebuild and redeploy.

export type PageMetaOverride = {
  metaTitleEn: string | null;
  metaTitleFr: string | null;
  metaTitleAr: string | null;
  metaDescriptionEn: string | null;
  metaDescriptionFr: string | null;
  metaDescriptionAr: string | null;
};

export const pageMetaOverrides: Record<string, PageMetaOverride> = {
  "certificates": {
    metaTitleEn: "Certificates & Quality Standards — Iris Polymere", metaTitleFr: "Certificats et Normes Qualité — Iris Polymere", metaTitleAr: "الشهادات ومعايير الجودة — Iris Polymere",
    metaDescriptionEn: "ISO 9001, REACH and RoHS reference standards guiding Iris Polymere's production and quality approach.", metaDescriptionFr: "Normes de référence ISO 9001, REACH et RoHS guidant l'approche qualité et production d'Iris Polymere.", metaDescriptionAr: "معايير مرجعية ISO 9001 وREACH وRoHS توجّه نهج الإنتاج والجودة لدى Iris Polymere.",
  }
};
