// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages). Re-run the
// export after publishing changes there, then rebuild and redeploy.

export type PageMetaOverride = {
  metaTitleEn: string | null;
  metaTitleFr: string | null;
  metaTitleAr: string | null;
  metaDescriptionEn: string | null;
  metaDescriptionFr: string | null;
  metaDescriptionAr: string | null;
};

export const pageMetaOverrides: Record<string, PageMetaOverride> = {
  "certificates": {
    metaTitleEn: "Certificates & Quality Standards — Iris Polymere", metaTitleFr: "Certificats et Normes Qualité — Iris Polymere", metaTitleAr: "الشهادات ومعايير الجودة — Iris Polymere",
    metaDescriptionEn: "ISO 9001, REACH and RoHS reference standards guiding Iris Polymere's production and quality approach.", metaDescriptionFr: "Normes de référence ISO 9001, REACH et RoHS guidant l'approche qualité et production d'Iris Polymere.", metaDescriptionAr: "معايير مرجعية ISO 9001 وREACH وRoHS توجّه نهج الإنتاج والجودة لدى Iris Polymere.",
  },
  "products/hffr-hm2": {
    metaTitleEn: "HM-2 HFFR Compound — Iris Polymere", metaTitleFr: "Compound HFFR HM-2 — Iris Polymere", metaTitleAr: "مركّب HM-2 من نوع HFFR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  },
  "products/hffr-hm4": {
    metaTitleEn: "HM-4 HFFR Compound — Iris Polymere", metaTitleFr: "Compound HFFR HM-4 — Iris Polymere", metaTitleAr: "مركّب HM-4 من نوع HFFR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  },
  "products/hffr-hm5": {
    metaTitleEn: "HM-5 HFFR Compound — Iris Polymere", metaTitleFr: "Compound HFFR HM-5 — Iris Polymere", metaTitleAr: "مركّب HM-5 من نوع HFFR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  },
  "products/hffr-bedding": {
    metaTitleEn: "HFFR Cable Bedding Compound — Iris Polymere", metaTitleFr: "Compound de Bourrage HFFR — Iris Polymere", metaTitleAr: "مركّب طبقة تبطين الكابلات HFFR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  },
  "products/hffr-filler": {
    metaTitleEn: "HFFR Filler Compound — Iris Polymere", metaTitleFr: "Compound de Charge HFFR — Iris Polymere", metaTitleAr: "مركّب حشو HFFR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  },
  "products/hffr-cpr": {
    metaTitleEn: "CPR-Related HFFR Compound — Iris Polymere", metaTitleFr: "Compound HFFR lié au CPR — Iris Polymere", metaTitleAr: "مركّب HFFR متعلق بـ CPR — Iris Polymere",
    metaDescriptionEn: null, metaDescriptionFr: null, metaDescriptionAr: null,
  }
};
