// Auto-generated by `npm run export-content` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages/corporate/*). Re-run
// the export after publishing changes there, then rebuild and redeploy.

export const pageHeroImages: Record<string, string> = {

};
