/**
 * Reads the local admin database (SQLite, edited via /admin) and
 * regenerates the site's static content data files. Run this after
 * publishing changes in the admin panel, then `npm run build` + redeploy
 * so the live site picks them up.
 */
import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { writeFile } from "fs/promises";
import path from "path";

const dbPath = path.join(process.cwd(), "dev.db");
const adapter = new PrismaLibSql({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

function esc(str: string) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function tri(en: string, fr: string | null, ar: string | null) {
  return `{ en: \`${esc(en)}\`, fr: \`${esc(fr || en)}\`, ar: \`${esc(ar || en)}\` }`;
}

async function main() {
  const posts = await prisma.post.findMany({
    where: { published: true },
    include: { category: true },
    orderBy: { publishedAt: "desc" },
  });

  const certificates = await prisma.certificate.findMany({ orderBy: { key: "asc" } });

  const blogEntries = posts.map((p) => {
    const category = p.category
      ? tri(p.category.nameEn, p.category.nameFr, p.category.nameAr)
      : "null";
    return `  {
    slug: ${JSON.stringify(p.slug)},
    categoryName: ${category},
    title: ${tri(p.titleEn, p.titleFr, p.titleAr)},
    excerpt: ${tri(p.excerptEn, p.excerptFr, p.excerptAr)},
    bodyHtml: ${tri(p.bodyEn, p.bodyFr, p.bodyAr)},
    coverImage: ${p.coverImage ? JSON.stringify(p.coverImage) : "null"},
    publishedAt: ${JSON.stringify((p.publishedAt ?? p.createdAt).toISOString())},
  }`;
  });

  const blogFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin). Re-run the export
// after publishing changes there, then rebuild and redeploy.

export type LocalizedText = { en: string; fr: string; ar: string };

export type BlogPost = {
  slug: string;
  categoryName: LocalizedText | null;
  title: LocalizedText;
  excerpt: LocalizedText;
  bodyHtml: LocalizedText;
  coverImage: string | null;
  publishedAt: string;
};

export const blogPosts: BlogPost[] = [
${blogEntries.join(",\n")}
];

export const blogPostsBySlug: Record<string, BlogPost> = Object.fromEntries(
  blogPosts.map((p) => [p.slug, p])
);
`;

  const certEntries = certificates.map((c) => {
    return `  {
    key: ${JSON.stringify(c.key)},
    title: ${tri(c.titleEn, c.titleFr, c.titleAr)},
    desc: ${tri(c.descEn, c.descFr, c.descAr)},
    pdfUrl: ${c.pdfUrl ? JSON.stringify(c.pdfUrl) : "null"},
  }`;
  });

  const certFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/certificates).

import type { LocalizedText } from "./blog";

export type CertificateData = {
  key: string;
  title: LocalizedText;
  desc: LocalizedText;
  pdfUrl: string | null;
};

export const certificates: CertificateData[] = [
${certEntries.join(",\n")}
];
`;

  await writeFile(path.join(process.cwd(), "lib/data/blog.ts"), blogFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/certificates.ts"), certFile, "utf-8");

  console.log(`Exported ${posts.length} published post(s) and ${certificates.length} certificate(s).`);
  console.log("Wrote lib/data/blog.ts and lib/data/certificates.ts");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
