/**
 * Reads the local admin database (SQLite, edited via /admin) and
 * regenerates the site's static content data files. Run this after
 * publishing changes in the admin panel, then `npm run build` + redeploy
 * so the live site picks them up.
 */
import { PrismaClient } from "../lib/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { writeFile } from "fs/promises";
import path from "path";

const dbPath = path.join(process.cwd(), "dev.db");
const adapter = new PrismaLibSql({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

function esc(str: string) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function tri(en: string, fr: string | null, ar: string | null) {
  return `{ en: \`${esc(en)}\`, fr: \`${esc(fr || en)}\`, ar: \`${esc(ar || en)}\` }`;
}

const SITE_SUFFIX = " — Iris Polymere";
const META_TITLE_TARGET = 60;

// Only append the site name to an auto-generated fallback title when it still
// fits within the ~60-char recommended <title> length; a long post title is
// better left bare than truncated or pushed past the SEO-recommended length.
function withBrandSuffix(title: string) {
  return title.length + SITE_SUFFIX.length <= META_TITLE_TARGET ? `${title}${SITE_SUFFIX}` : title;
}

async function main() {
  const posts = await prisma.post.findMany({
    where: { published: true },
    include: { category: true },
    orderBy: { publishedAt: "desc" },
  });

  const certificates = await prisma.certificate.findMany({ orderBy: { key: "asc" } });
  const pageMetas = await prisma.pageMeta.findMany();
  const banners = await prisma.banner.findMany({ orderBy: { order: "asc" } });
  const siteAssets = await prisma.siteAsset.findMany();
  const corporateHeroImages = await prisma.corporateHeroImage.findMany();
  const productImages = await prisma.productImage.findMany();

  const blogEntries = posts.map((p) => {
    const category = p.category
      ? tri(p.category.nameEn, p.category.nameFr, p.category.nameAr)
      : "null";
    // SEO fields fall back to title / excerpt per-locale when left blank.
    // A custom meta title is used verbatim (it's the final <title>, same as
    // WordPress SEO plugins); only the auto-generated fallback gets the
    // site name appended, since the raw post title never includes it.
    const metaTitle = tri(
      p.metaTitleEn || withBrandSuffix(p.titleEn),
      p.metaTitleFr || withBrandSuffix(p.titleFr || p.titleEn),
      p.metaTitleAr || withBrandSuffix(p.titleAr || p.titleEn)
    );
    const metaDescription = tri(
      p.metaDescriptionEn || p.excerptEn,
      p.metaDescriptionFr || p.excerptFr,
      p.metaDescriptionAr || p.excerptAr
    );
    return `  {
    slug: ${JSON.stringify(p.slug)},
    categoryName: ${category},
    title: ${tri(p.titleEn, p.titleFr, p.titleAr)},
    excerpt: ${tri(p.excerptEn, p.excerptFr, p.excerptAr)},
    bodyHtml: ${tri(p.bodyEn, p.bodyFr, p.bodyAr)},
    metaTitle: ${metaTitle},
    metaDescription: ${metaDescription},
    coverImage: ${p.coverImageEn ? tri(p.coverImageEn, p.coverImageFr, p.coverImageAr) : "null"},
    publishedAt: ${JSON.stringify((p.publishedAt ?? p.createdAt).toISOString())},
  }`;
  });

  const blogFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin). Re-run the export
// after publishing changes there, then rebuild and redeploy.

export type LocalizedText = { en: string; fr: string; ar: string };

export type BlogPost = {
  slug: string;
  categoryName: LocalizedText | null;
  title: LocalizedText;
  excerpt: LocalizedText;
  bodyHtml: LocalizedText;
  metaTitle: LocalizedText;
  metaDescription: LocalizedText;
  coverImage: LocalizedText | null;
  publishedAt: string;
};

export const blogPosts: BlogPost[] = [
${blogEntries.join(",\n")}
];

export const blogPostsBySlug: Record<string, BlogPost> = Object.fromEntries(
  blogPosts.map((p) => [p.slug, p])
);
`;

  const certEntries = certificates.map((c) => {
    return `  {
    key: ${JSON.stringify(c.key)},
    title: ${tri(c.titleEn, c.titleFr, c.titleAr)},
    desc: ${tri(c.descEn, c.descFr, c.descAr)},
    pdfUrl: ${c.pdfUrl ? JSON.stringify(c.pdfUrl) : "null"},
  }`;
  });

  const certFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/certificates).

import type { LocalizedText } from "./blog";

export type CertificateData = {
  key: string;
  title: LocalizedText;
  desc: LocalizedText;
  pdfUrl: string | null;
};

export const certificates: CertificateData[] = [
${certEntries.join(",\n")}
];
`;

  const pageMetaEntries = pageMetas.map((p) => {
    const field = (v: string | null) => (v ? JSON.stringify(v) : "null");
    return `  ${JSON.stringify(p.key)}: {
    metaTitleEn: ${field(p.metaTitleEn)}, metaTitleFr: ${field(p.metaTitleFr)}, metaTitleAr: ${field(p.metaTitleAr)},
    metaDescriptionEn: ${field(p.metaDescriptionEn)}, metaDescriptionFr: ${field(p.metaDescriptionFr)}, metaDescriptionAr: ${field(p.metaDescriptionAr)},
  }`;
  });

  const pageMetaFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages). Re-run the
// export after publishing changes there, then rebuild and redeploy.

export type PageMetaOverride = {
  metaTitleEn: string | null;
  metaTitleFr: string | null;
  metaTitleAr: string | null;
  metaDescriptionEn: string | null;
  metaDescriptionFr: string | null;
  metaDescriptionAr: string | null;
};

export const pageMetaOverrides: Record<string, PageMetaOverride> = {
${pageMetaEntries.join(",\n")}
};
`;

  const bannerEntries = banners.map((b) => {
    return `  {
    url: ${tri(b.urlEn, b.urlFr, b.urlAr)},
    altText: { en: ${b.altTextEn ? JSON.stringify(b.altTextEn) : "null"}, fr: ${b.altTextFr ? JSON.stringify(b.altTextFr) : b.altTextEn ? JSON.stringify(b.altTextEn) : "null"}, ar: ${b.altTextAr ? JSON.stringify(b.altTextAr) : b.altTextEn ? JSON.stringify(b.altTextEn) : "null"} },
  }`;
  });

  const bannersFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/banners). Re-run the
// export after publishing changes there, then rebuild and redeploy.

import type { LocalizedText } from "./blog";

export type Banner = { url: LocalizedText; altText: { en: string | null; fr: string | null; ar: string | null } };

export const banners: Banner[] = [
${bannerEntries.join(",\n")}
];
`;

  // favicon/apple-icon are excluded — Next reads those straight from
  // app/icon.png and app/apple-icon.png at build time, no data file needed.
  const siteAssetEntries = siteAssets
    .filter((a) => a.key !== "favicon" && a.key !== "apple-icon")
    .map((a) => `  ${JSON.stringify(a.key)}: ${JSON.stringify(a.url)}`);

  const siteAssetsFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/assets). Re-run the
// export after publishing changes there, then rebuild and redeploy.

export const siteAssetOverrides: Record<string, string> = {
${siteAssetEntries.join(",\n")}
};
`;

  const corporateHeroEntries = corporateHeroImages.map((c) => {
    return `  ${JSON.stringify(c.slug)}: ${tri(c.urlEn, c.urlFr, c.urlAr)}`;
  });

  const corporateImagesFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/pages/about). Re-run the
// export after publishing changes there, then rebuild and redeploy.

import type { LocalizedText } from "./blog";

export const corporateHeroImages: Record<string, LocalizedText> = {
${corporateHeroEntries.join(",\n")}
};
`;

  const productImageEntries = productImages.map((p) => `  ${JSON.stringify(p.slug)}: ${JSON.stringify(p.url)}`);

  const productImagesFile = `// Auto-generated by \`npm run export-content\` — do not edit by hand.
// Source of truth: the local admin database (/admin/product-images). Re-run
// the export after publishing changes there, then rebuild and redeploy.

export const productImages: Record<string, string> = {
${productImageEntries.join(",\n")}
};
`;

  await writeFile(path.join(process.cwd(), "lib/data/blog.ts"), blogFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/certificates.ts"), certFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/page-meta.ts"), pageMetaFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/banners.ts"), bannersFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/site-assets.ts"), siteAssetsFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/corporate-images.ts"), corporateImagesFile, "utf-8");
  await writeFile(path.join(process.cwd(), "lib/data/product-images.ts"), productImagesFile, "utf-8");

  console.log(`Exported ${posts.length} published post(s), ${certificates.length} certificate(s), ${pageMetas.length} page meta override(s), ${banners.length} banner(s), ${siteAssetEntries.length} site asset override(s), ${corporateHeroImages.length} corporate hero image(s), ${productImages.length} product image(s).`);
  console.log("Wrote lib/data/blog.ts, lib/data/certificates.ts, lib/data/page-meta.ts, lib/data/banners.ts, lib/data/site-assets.ts, lib/data/corporate-images.ts and lib/data/product-images.ts");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
